### ISSUE TITLE
Releases with per-platform executables

### ISSUE THREAD

**Issue by baronfel** [CtrlSpice/otel-desktop-viewer#101]
Hello! I would very much like to use this project as a standalone viewer for traces emitted by my language's compiler in the [LSP Server I maintain](https://github.com/fsharp/FsAutoComplete), and to do so I'd like to be able to download the prebuilt release binaries for this project from a releases page here.

Would you accept some kind of releases CI pipeline as a contribution? I'm fairly handy with them and would love to help out.

**Comment by CtrlSpice** [comment]
Hey! Yes, that would be very welcome! I was planning on tackling release binaries using GoReleaser, just haven't had the chance to yet and I am not super experienced with CI pipelines in general (yet!) so any help would be super appreciated.
Thank you so much!
