### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by EddieEldridge** [CtrlSpice/otel-desktop-viewer#83]
2023/02/14 08:55:29 http: Accept error: accept tcp 127.0.0.1:4318: accept: too many open files; retrying in 10ms

I get this error when trying to start up the Collector. Any ideas?

**Comment by EddieEldridge** [comment]
Update: I still got it to work but not sure what this error is all about.

**Comment by CtrlSpice** [comment]
Hey there,

So I looked into my open file descriptor situation and I don't think this is an issue with this application specifically, but you may need to increase your ulimit.

I used this article to debug: https://www.imakewebsites.ca/posts/nodejs-too-many-open-files-ulimit/
(swap out node for otel-desktop-collector where needed 😄) and the file descriptor stays fairly low, with these being relevant to the ports we have open:
 
`otel-desk 71330 amelia 11u  IPv4 TCP localhost:4317 (LISTEN)`
`otel-desk 71330 amelia 12u  IPv4 TCP localhost:irdmi (LISTEN)`
`otel-desk 71330 amelia 13u  IPv4 TCP localhost:4318 (LISTEN)`
`otel-desk 71330 amelia 16u  IPv4 TCP localhost:irdmi->localhost:59613 (ESTABLISHED)`
`otel-desk 71330 amelia  17u IPv4 TCP localhost:irdmi->localhost:59614 (ESTABLISHED)`

Try it out to see if there is anything else going on, and of course you find it is my app acting weird, reopen and let me know!
