### ISSUE TITLE
Expanding Scope Data  appears truncated by scroll

### ISSUE THREAD

**Issue by ArielGMachado** [CtrlSpice/otel-desktop-viewer#84]
First of all, let me say you did an amazing tool. Thank you!  Thank you!. Now  in addition to traces, I want more!: I want to visualize OTLP Metrics and Logs! :rofl: 

Now seriously and putting my ambitious expectations aside, I just want to report a minor issue with the scroll page when  Scope Data is expanded appears truncated:
![ExpandedScopeDataCrop](https://user-images.githubusercontent.com/124715468/218702919-23200139-fa21-4dea-b884-155767052d66.png)

**Comment by CtrlSpice** [comment]
Hi there,
I am so glad you are enjoying the tool, and thank you so much for pointing out this issue. 
It should be all fixed up in now (#91). 😄
